inherit_from: default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  EnabledByDefault: true
  NewCops: enable

Layout:
  Severity: error
Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint:
  Severity: error

Style:
  Severity: error
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: false
Style/NegatedIf:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%i': '()'
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma